### ISSUE TITLE
let g:tene_ga["line()"] E121: Undefined variable: g:tene_ga

### ISSUE THREAD

**Issue by DanielViberg** [kennypete/vim-tene#1]
Thanks for this great plugin.

Getting E121: Undefined variable: g:tene_ga when i try to set let g:tene_ga, both in vim9scrip and legacy script. 

Vim legacy: `let g:tene_ga["line()"]`
Vim9: `g:tene_ga["line()"]`

**Comment by kennypete** [comment]
Thanks, I love it too (though I'm biased, aye).

I just added `g:tene_ga["line()"] = ['_', '☺️'] ` to my (vim9script) `_vimrc` and it works fine (Windows and WSL):

![image](https://github.com/user-attachments/assets/527a4bc4-c07a-4a4f-bd39-7607248fca5d)
![image](https://github.com/user-attachments/assets/6d7f7300-ca50-470a-bf4a-f0560745d0e2)

**Comment by DanielViberg** [comment]
Silly me, i should have read the docs more thoroughly. Thanks!
